import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';
// import commonjs from '@rollup/plugin-commonjs';

export default defineConfig({
    base: 'https://rates.visualorders.com/public/',
    plugins: [
        laravel({
            input: [
                'resources/scss/config/default/app.scss',
                'resources/scss/config/default/bootstrap.scss',
                'resources/scss/config/creative/app.scss',
                'resources/scss/config/creative/bootstrap.scss',
                'resources/scss/config/modern/app.scss',
                'resources/scss/config/modern/bootstrap.scss',
                'resources/scss/config/material/app.scss',
                'resources/scss/config/material/bootstrap.scss',
                'resources/scss/config/purple/app.scss',
                'resources/scss/config/purple/bootstrap.scss',
                'resources/scss/config/saas/app.scss',
                'resources/scss/config/saas/bootstrap.scss',
                'resources/scss/icons.scss',
                'resources/scss/landing.scss',
                'resources/js/pages/crm-opportunities.init.js',
                'resources/js/pages/crm-leads.init.js',
                'resources/js/pages/inbox.js',


                'node_modules/apexcharts/dist/apexcharts.css',
                'node_modules/admin-resources/jquery.vectormap/jquery-jvectormap-1.2.2.css',
                'node_modules/admin-resources/rwd-table/rwd-table.min.css',
                // 'node_modules/admin-resources/admin-resources.min.css',
                'node_modules/flatpickr/dist/flatpickr.min.css',
                'node_modules/fullcalendar/main.min.css',
                'node_modules/select2/dist/css/select2.min.css',
                'node_modules/dropzone/dist/min/dropzone.min.css',
                'node_modules/quill/dist/quill.core.css',
                'node_modules/quill/dist/quill.snow.css',
                'node_modules/quill/dist/quill.bubble.css',
                'node_modules/datatables.net-bs5/css/dataTables.bootstrap5.min.css',
                'node_modules/datatables.net-responsive-bs5/css/responsive.bootstrap5.min.css',
                // 'node_modules/dragula/dist/dragula.min.css',
                'node_modules/magnific-popup/dist/magnific-popup.css',
                'node_modules/jquery-toast-plugin/dist/jquery.toast.min.css',
                'node_modules/nestable2/dist/jquery.nestable.min.css',
                'node_modules/ion-rangeslider/css/ion.rangeSlider.min.css',
                // 'node_modules/animate.css/animate.min.css',
                'node_modules/animate.css/animate.compat.css',
                'node_modules/sweetalert2/dist/sweetalert2.min.css',
                'node_modules/hopscotch/dist/css/hopscotch.min.css',
                'node_modules/ladda/dist/ladda.min.css',
                'node_modules/ladda/dist/ladda-themeless.min.css',
                'node_modules/selectize/dist/css/selectize.bootstrap3.css',
                'node_modules/mohithg-switchery/dist/switchery.min.css',
                'node_modules/multiselect/css/multi-select.css',
                'node_modules/bootstrap-touchspin/dist/jquery.bootstrap-touchspin.min.css',
                'node_modules/spectrum-colorpicker2/dist/spectrum.min.css',
                'node_modules/clockpicker/dist/bootstrap-clockpicker.min.css',
                'node_modules/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css',
                'node_modules/dropify/dist/css/dropify.min.css',
                'node_modules/x-editable/dist/bootstrap-editable/css/bootstrap-editable.css',
                'node_modules/cropper/dist/cropper.min.css',
                'node_modules/datatables.net-buttons-bs5/css/buttons.bootstrap5.min.css',
                'node_modules/datatables.net-select-bs5/css/select.bootstrap5.min.css',
                'node_modules/bootstrap-table/dist/bootstrap-table.min.css',
                'node_modules/tablesaw/dist/tablesaw.css',
                'node_modules/jsgrid/dist/jsgrid.min.css',
                'node_modules/jsgrid/dist/jsgrid-theme.min.css',
                'node_modules/chartist/dist/chartist.min.css',
                'node_modules/c3/c3.min.css',
                // 'node_modules/jquery-mousewheel.min.js/jquery.mousewheel.min.js',




                'resources/js/app.js',
                'resources/js/head.js',
                'resources/js/head-2.js',
                'resources/js/layout.js',

                'node_modules/bootstrap/dist/js/bootstrap.bundle.min.js',
//                'node_modules/jquery/dist/jquery.js',

                'node_modules/simplebar/dist/simplebar.js',
                'node_modules/apexcharts/dist/apexcharts.min.js',
                'node_modules/jquery-sparkline/jquery.sparkline.min.js',
                'node_modules/flatpickr/dist/flatpickr.min.js',
                'node_modules/chart.js/dist/Chart.bundle.min.js',
                'node_modules/morris.js06/dist/morris.min.js',
                'node_modules/moment/min/moment.min.js',
                // 'node_modules/moment/src/moment.js',
                'node_modules/fullcalendar/main.min.js',
                'node_modules/select2/dist/js/select2.min.js',
                'node_modules/dropzone/dist/min/dropzone.min.js',
                'node_modules/quill/dist/quill.min.js',
                'node_modules/datatables.net/js/jquery.dataTables.min.js',
                'node_modules/datatables.net-bs5/js/dataTables.bootstrap5.min.js',
                'node_modules/datatables.net-responsive/js/dataTables.responsive.min.js',
                'node_modules/datatables.net-responsive-bs5/js/responsive.bootstrap5.min.js',
                'node_modules/jquery-datatables-checkboxes/js/dataTables.checkboxes.min.js',
                'node_modules/raphael/raphael.min.js',
                'node_modules/dragula/dist/dragula.min.js',
                'node_modules/sortablejs/Sortable.min.js',
                'node_modules/magnific-popup/dist/jquery.magnific-popup.min.js',
                'node_modules/jquery-toast-plugin/dist/jquery.toast.min.js',
                'node_modules/tippy.js/dist/tippy.all.min.js',
                'node_modules/nestable2/dist/jquery.nestable.min.js',
                'node_modules/ion-rangeslider/js/ion.rangeSlider.min.js',
                'node_modules/sweetalert2/dist/sweetalert2.min.js',
                'node_modules/hopscotch/dist/js/hopscotch.min.js',
                'node_modules/ladda/dist/spin.min.js',
                'node_modules/ladda/dist/ladda.min.js',
                'node_modules/peity/jquery.peity.min.js',
                'node_modules/jquery-knob/dist/jquery.knob.min.js',
                'node_modules/selectize/dist/js/standalone/selectize.js',
                'node_modules/mohithg-switchery/dist/switchery.min.js',
                'node_modules/multiselect/js/jquery.multi-select.js',
                'node_modules/jquery-mockjax/dist/jquery.mockjax.min.js',
                'node_modules/devbridge-autocomplete/dist/jquery.autocomplete.min.js',
                'node_modules/bootstrap-touchspin/dist/jquery.bootstrap-touchspin.min.js',
                'node_modules/bootstrap-maxlength/dist/bootstrap-maxlength.min.js',
                'node_modules/parsleyjs/dist/parsley.min.js',
                'node_modules/spectrum-colorpicker2/dist/spectrum.min.js',
                'node_modules/clockpicker/dist/bootstrap-clockpicker.min.js',
                'node_modules/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js',
                'node_modules/twitter-bootstrap-wizard/jquery.bootstrap.wizard.min.js',
                'node_modules/jquery-mask-plugin/dist/jquery.mask.min.js',
                'node_modules/autonumeric/dist/autoNumeric.min.js',
                'node_modules/dropify/dist/js/dropify.min.js',
                'node_modules/x-editable/dist/bootstrap-editable/js/bootstrap-editable.min.js',
                'node_modules/cropper/dist/cropper.min.js',
                'node_modules/datatables.net-buttons/js/dataTables.buttons.min.js',
                'node_modules/datatables.net-buttons-bs5/js/buttons.bootstrap5.min.js',
                'node_modules/datatables.net-buttons/js/buttons.html5.min.js',
                'node_modules/datatables.net-buttons/js/buttons.flash.min.js',
                'node_modules/datatables.net-buttons/js/buttons.print.min.js',
                'node_modules/datatables.net-keytable/js/dataTables.keyTable.min.js',
                'node_modules/datatables.net-select/js/dataTables.select.min.js',
                'node_modules/pdfmake/build/pdfmake.min.js',
                'node_modules/pdfmake/build/vfs_fonts.js',
                'node_modules/jquery-tabledit/jquery.tabledit.min.js',
                'node_modules/jquery-mapael/js/jquery.mapael.min.js',
                'node_modules/jquery-mapael/js/maps/world_countries.min.js',
                'node_modules/jquery-mapael/js/maps/usa_states.min.js',
                'node_modules/footable/dist/footable.all.min.js',
                'node_modules/bootstrap-table/dist/bootstrap-table.min.js',
                'node_modules/tablesaw/dist/tablesaw.js',
                'node_modules/jsgrid/dist/jsgrid.min.js',
                'node_modules/flot-charts/jquery.flot.js',
                'node_modules/flot-charts/jquery.flot.time.js',
                'node_modules/flot-charts/jquery.flot.resize.js',
                'node_modules/flot-charts/jquery.flot.pie.js',
                'node_modules/flot-charts/jquery.flot.selection.js',
                'node_modules/flot-charts/jquery.flot.stack.js',
                'node_modules/flot-charts/jquery.flot.crosshair.js',
                'node_modules/jquery.flot.tooltip/js/jquery.flot.tooltip.min.js',
                'node_modules/flot-orderbars/js/jquery.flot.orderBars.js',
                'node_modules/chartist/dist/chartist.min.js',
                'node_modules/chartist-plugin-tooltips/dist/chartist-plugin-tooltip.min.js',
                'node_modules/d3/dist/d3.min.js',
                'node_modules/c3/c3.min.js',
                'node_modules/gmaps/gmaps.min.js',
                'node_modules/waypoints/lib/jquery.waypoints.js',
                'node_modules/jquery.counterup/jquery.counterup.js',




                'resources/js/pages/morris.init.js',
                'resources/js/pages/dashboard-1.init.js',
                'resources/js/pages/dashboard-2.init.js',
                'resources/js/pages/dashboard-3.init.js',
                'resources/js/pages/dashboard-4.init.js',
                'resources/js/pages/ecommerce-dashboard.init.js',
                'resources/js/pages/calendar.init.js',
                'resources/js/pages/form-fileuploads.init.js',
                'resources/js/pages/add-product.init.js',
                'resources/js/pages/customers.init.js',
                'resources/js/pages/crm-dashboard.init.js',
                'resources/js/pages/project-details.init.js',
                'resources/js/pages/create-project.init.js',
                'resources/js/pages/dragula.init.js',
                'resources/js/pages/task.init.js',
                'resources/js/pages/kanban.init.js',
                'resources/js/pages/tickets.js',
                'resources/js/pages/gallery.init.js',
                'resources/js/pages/toastr.init.js',
                'resources/js/pages/nestable.init.js',
                'resources/js/pages/range-sliders.init.js',
                'resources/js/pages/animation.init.js',
                'resources/js/pages/sweet-alerts.init.js',
                'resources/js/pages/tour.init.js',
                'resources/js/pages/loading-btn.init.js',
                'resources/js/pages/widgets.init.js',
                'resources/js/pages/jquery.todo.js',
                'resources/js/pages/jquery.chat.js',
                'resources/js/pages/fontawesome.init.js',
                'resources/js/pages/material-symbols.init.js',
                'resources/js/pages/materialdesign.init.js',
                'resources/js/pages/form-advanced.init.js',
                'resources/js/pages/form-validation.init.js',
                'resources/js/pages/form-pickers.init.js',
                'resources/js/pages/form-wizard.init.js',
                'resources/js/pages/form-masks.init.js',
                'resources/js/pages/form-quilljs.init.js',
                'resources/js/pages/form-fileuploads.init.js',
                'resources/js/pages/form-xeditable.init.js',
                'resources/js/pages/form-imagecrop.init.js',
                'resources/js/pages/datatables.init.js',
                'resources/js/pages/tabledit.init.js',
                'resources/js/pages/responsive-table.init.js',
                'resources/js/pages/foo-tables.init.js',
                'resources/js/pages/bootstrap-tables.init.js',
                'resources/js/pages/tablesaw.init.js',
                'resources/js/pages/jsgrid.init.js',
                'resources/js/pages/apexcharts.init.js',
                'resources/js/pages/flot.init.js',
                'resources/js/pages/chartjs.init.js',
                'resources/js/pages/peity.init.js',
                'resources/js/pages/chartist.init.js',
                'resources/js/pages/c3.init.js',
                'resources/js/pages/sparkline.init.js',
                'resources/js/pages/widgets-peity.init.js',
                'resources/js/pages/google-maps.init.js',
                'resources/js/pages/mapeal-maps.init.js',
                'resources/js/pages/compose.init.js',

                'node_modules/admin-resources/rwd-table/rwd-table.min.js',
                'node_modules/admin-resources/jquery.vectormap/jquery-jvectormap-1.2.2.min.js',
                'node_modules/admin-resources/jquery.vectormap/maps/jquery-jvectormap-world-mill-en.js',
                'node_modules/admin-resources/jquery.vectormap/maps/jquery-jvectormap-us-merc-en.js',
                'node_modules/admin-resources/jquery.vectormap/maps/jquery-jvectormap-in-mill-en.js',
                'node_modules/admin-resources/jquery.vectormap/maps/jquery-jvectormap-au-mill-en.js',
                'node_modules/admin-resources/jquery.vectormap/maps/jquery-jvectormap-us-il-chicago-mill-en.js',
                'node_modules/admin-resources/jquery.vectormap/maps/jquery-jvectormap-uk-mill-en.js',
                'node_modules/admin-resources/jquery.vectormap/maps/jquery-jvectormap-ca-lcc-en.js',
                'node_modules/admin-resources/jquery.vectormap/maps/jquery-jvectormap-europe-mill-en.js',
                'node_modules/admin-resources/jquery.vectormap/maps/jquery-jvectormap-fr-merc-en.js',
                'node_modules/admin-resources/jquery.vectormap/maps/jquery-jvectormap-es-merc.js',
                'node_modules/admin-resources/jquery.vectormap/maps/jquery-jvectormap-es-mill.js',
                // 'node_modules/admin-resources/admin-resources.min.js',
                'resources/js/pages/vector-maps.init.js',
            ],
            refresh: true,


        }),
        // commonjs()
    ],

    build: {
        sourcemap: false,

    },
    // build: {
    //     commonjsOptions: {
    //         include: [/lib-cjs/, /node_modules/],
    //     },
    // },
    resolve: {
        alias: {
            '$': 'jQuery',
        },
    },

});


